import { test, expect, type Route } from '@playwright/test';

test('manual location search cancels cleanly, preserves failed queries, and retries', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('paddletoday:welcome-completed:v1', '1'));
  await page.route('**/api/**', (route) => route.fulfill({ status: 503, json: { error: 'offline' } }));
  await page.route('**/api/rivers/summary.json', (route) => route.fulfill({ json: { rivers: [] } }));
  const requests: Route[] = [];
  await page.route('https://geocoding-api.open-meteo.com/**', (route) => { requests.push(route); });
  await page.goto('/');
  const open = page.getByRole('button', { name: 'Set city or ZIP code', exact: true });
  await open.click();
  const dialog = page.getByRole('dialog');
  const input = dialog.getByRole('textbox', { name: 'City, state, or ZIP code', exact: true });
  const submit = dialog.getByRole('button', { name: 'Use this location', exact: true });
  await input.fill('Old city');
  await submit.click();
  await expect(submit).toBeDisabled();
  await expect(submit).toHaveAttribute('aria-busy', 'true');
  await expect(input).toHaveAttribute('readonly', '');
  await submit.dispatchEvent('click');
  await expect.poll(() => requests.length).toBe(1);
  await dialog.getByRole('button', { name: 'Close location search', exact: true }).click();
  await open.click();
  await input.fill('New city');
  await requests[0].fulfill({ json: { results: [{ latitude: 45, longitude: -93, name: 'Old city', admin1: 'Minnesota' }] } });
  await expect(input).toHaveValue('New city');
  await expect(submit).toBeEnabled();
  await submit.click();
  await expect.poll(() => requests.length).toBe(2);
  await requests[1].fulfill({ json: { results: [{ latitude: 145, longitude: -93, name: 'Invalid coordinates', admin1: 'Minnesota' }] } });
  await expect(dialog.getByText("We couldn't find that city or ZIP code.", { exact: true })).toBeVisible();
  await expect(input).toHaveValue('New city');
  await expect(input).toBeEditable();
  await submit.click();
  await expect.poll(() => requests.length).toBe(3);
  await requests[2].fulfill({ json: { results: [{ latitude: 45.1, longitude: -93.2, name: 'New city', admin1: 'Minnesota' }] } });
  await expect(dialog).toBeHidden();
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('paddletoday:user-location')!))).toMatchObject({ latitude: 45.1, longitude: -93.2, label: 'New city, Minnesota' });
});
