import { test, expect, type Route } from '@playwright/test';

test('route requests explain field errors and preserve entries through failed submission', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('paddletoday:welcome-completed:v1', '1'));
  await page.route('**/api/**', route => route.fulfill({ status: 503, json: { error: 'offline' } }));
  let pending: Route | undefined;
  let requests = 0;
  await page.route('**/api/route-request', route => { requests++; pending = route; });
  await page.goto('/request-route');
  const river = page.getByRole('textbox', { name: 'River name', exact: true });
  const area = page.getByRole('textbox', { name: 'City, state, or general area', exact: true });
  const email = page.getByRole('textbox', { name: 'Your email', exact: true });
  const send = page.getByRole('button', { name: 'Send request', exact: true });
  await send.click();
  await expect(river).toBeFocused();
  await expect(river).toHaveAttribute('aria-invalid', 'true');
  await expect(river).toHaveAttribute('aria-required', 'true');
  await expect(page.getByText('Add a river or route name with at least three characters.', { exact: true }).first()).toBeInViewport();
  await river.fill('QA Creek');
  await expect(river).toHaveAttribute('aria-invalid', 'false');
  await send.click();
  await expect(area).toBeFocused();
  await area.fill('MN');
  await email.fill('bad-email');
  await send.click();
  await expect(email).toBeFocused();
  await expect(page.getByText('Enter a valid email address or leave this field blank.', { exact: true })).toBeInViewport();
  await page.screenshot({ path: `tmp/route-request-validation-${page.viewportSize()!.width}.png` });
  await email.fill('QA@EXAMPLE.COM');
  await page.getByRole('textbox', { name: 'Notes', exact: true }).fill('Quiet launch near the bridge');
  await send.click();
  await expect(send).toBeDisabled();
  await expect(send).toHaveAttribute('aria-busy', 'true');
  await expect(river).not.toBeEditable();
  await expect.poll(() => pending !== undefined).toBe(true);
  expect(pending!.request().postDataJSON().replyEmail).toBe('qa@example.com');
  expect(requests).toBe(1);
  await pending!.fulfill({ status: 503, json: { message: 'Please try again shortly.' } });
  await expect(send).toBeEnabled();
  await expect(river).toHaveValue('QA Creek');
  await expect(page.getByRole('textbox', { name: 'Notes', exact: true })).toHaveValue('Quiet launch near the bridge');
  pending = undefined;
  await send.click();
  await expect.poll(() => pending !== undefined).toBe(true);
  await pending!.fulfill({ status: 202, json: { ok: true, stored: true, requestId: 'qa' } });
  await expect(page.getByText('Request received. Thanks for the lead.', { exact: true })).toBeVisible();
  await expect(river).toHaveValue('');
  await expect(river).toHaveAttribute('aria-invalid', 'false');
  expect(requests).toBe(2);
});
