import { test, expect, type Route } from '@playwright/test';
import fixture from './fixtures/route-detail.json' with { type: 'json' };
test('route reports preserve drafts and show confirmation after retry', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('paddletoday:welcome-completed:v1', '1'));
  await page.route('**/api/**', (route) => route.fulfill({ status: 503, json: { error: 'offline', message: 'Offline test' } }));
  await page.route('**/api/rivers/rice-creek-peltier-to-long-lake.json', (route) => route.fulfill({ json: fixture }));
  let pending: Route | null = null;
  let requests = 0;
  await page.route('**/api/route-contributions', (route) => { pending = route; requests++; });
  await page.goto('/river/rice-creek-peltier-to-long-lake');
  await page.getByText('Reports', { exact: true }).click();
  await page.getByText('Report', { exact: true }).click();
  const dialog = page.getByRole('dialog');
  const name = dialog.getByRole('textbox', { name: 'Contributor name or paddling handle' });
  const email = dialog.getByRole('textbox', { name: 'Email address', exact: true });
  const report = dialog.getByRole('textbox', { name: 'Route report', exact: true });
  const send = dialog.getByRole('button', { name: 'Send report', exact: true });
  await send.click();
  await expect(name).toBeFocused();
  await expect(name).toHaveAttribute('aria-invalid', 'true');
  await name.fill('QA Paddler');
  await expect(name).toHaveAttribute('aria-invalid', 'false');
  await send.click();
  await expect(email).toBeFocused();
  await email.fill('qa@example.com');
  await send.click();
  await expect(report).toBeFocused();
  await report.fill('The route was clear and the access was easy to find.');
  await send.click();
  await expect(dialog.getByText('Choose the water level you observed. Unknown is available if you are unsure.', { exact: true })).toBeInViewport();
  await page.screenshot({ path: `tmp/report-choice-validation-${page.viewportSize()!.width}.png` });
  await dialog.getByRole('button', { name: 'Observed water level: Ideal', exact: true }).click();
  await expect(dialog.getByText('Choose the water level you observed. Unknown is available if you are unsure.', { exact: true })).toHaveCount(0);
  await send.click();
  await expect(dialog.getByText('Choose the trip outcome.', { exact: true })).toBeInViewport();
  await dialog.getByRole('button', { name: 'Trip outcome: Completed', exact: true }).click();
  await send.click();
  await expect(dialog.getByText('Choose an overall verdict.', { exact: true })).toBeInViewport();
  await dialog.getByRole('button', { name: 'Overall verdict: Good', exact: true }).click();
  await send.click();
  await expect(dialog.getByText("Confirm that it's okay to contact you about this report.", { exact: true })).toBeInViewport();
  await dialog.getByRole('checkbox', { name: 'I agree to follow-up questions.', exact: true }).check();
  await expect(dialog.getByText("Confirm that it's okay to contact you about this report.", { exact: true })).toHaveCount(0);
  await dialog.getByRole('button', { name: 'Send report', exact: true }).click();
  await expect.poll(() => Boolean(pending)).toBe(true);
  await expect(report).not.toBeEditable();
  await expect(dialog.getByRole('button', { name: 'Overall verdict: Good', exact: true })).toBeDisabled();
  await expect(dialog.getByRole('button', { name: 'Add report photos', exact: true })).toBeDisabled();
  expect(requests).toBe(1);
  await pending!.fulfill({ json: { ok: true, stored: false } });
  await expect(dialog.getByText('Your submission was not saved. Please try again.', { exact: true })).toBeVisible();
  await expect(report).toHaveValue('The route was clear and the access was easy to find.');
  pending = null;
  await dialog.getByRole('button', { name: 'Send report', exact: true }).click();
  await expect.poll(() => Boolean(pending)).toBe(true);
  await dialog.getByRole('button', { name: 'Close route report' }).click();
  await expect(dialog).toBeHidden();
  await page.getByRole('button', { name: 'View pending route report', exact: true }).click();
  await expect(report).not.toBeEditable();
  await pending!.fulfill({ json: { ok: true, stored: true } });
  await expect(dialog.getByText('Thank you. Your report was sent for review.', { exact: true })).toBeVisible();
  await expect(report).toHaveValue('');
  await dialog.getByRole('button', { name: 'Close route report', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Send route report', exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'Go back', exact: true }).click();
  await expect(page).not.toHaveURL(/\/river\//);
  await expect(page.getByRole('dialog')).toHaveCount(0);
  console.log('Route report drafts, pending reopen, choices, retry, and visible confirmation passed.');
});

