import { mkdir, rename, unlink, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { rivers } from '../src/data/rivers';
import { auditRouteSafety, routeSafetyAuditSummary, type RouteSafetyAuditIssue } from '../src/lib/route-safety-audit';

const jsonPath = path.join('docs', 'route-safety-audit.json');
const markdownPath = path.join('docs', 'route-safety-audit.md');

function makeMarkdown(args: {
  generatedAt: string;
  issues: RouteSafetyAuditIssue[];
}) {
  const summary = routeSafetyAuditSummary(args.issues);
  const lines = [
    '# Route Safety Audit',
    '',
    `Generated: ${args.generatedAt}`,
    '',
    'This report is generated by `npm run routes:safety:audit`. Use it to prioritize manual route safety review; do not hand-edit this file.',
    '',
    '## Summary',
    '',
    `- Routes scanned: ${rivers.length}`,
    `- Issues found: ${args.issues.length}`,
    `- Critical: ${summary.Critical}`,
    `- High: ${summary.High}`,
    `- Medium: ${summary.Medium}`,
    `- Low: ${summary.Low}`,
    '',
  ];

  const severities = ['Critical', 'High', 'Medium', 'Low'] as const;
  for (const severity of severities) {
    const issues = args.issues.filter((issue) => issue.severity === severity);
    lines.push(`## ${severity}`, '');

    if (issues.length === 0) {
      lines.push('No issues.', '');
      continue;
    }

    for (const issue of issues) {
      lines.push(`### ${issue.state} - ${issue.name}: ${issue.reach}`);
      lines.push('');
      lines.push(`- Route: \`${issue.slug}\``);
      lines.push(`- Category: ${issue.category}`);
      lines.push(`- Issue: ${issue.message}`);
      lines.push(`- Evidence: ${issue.evidence}`);
      lines.push('');
    }
  }

  return `${lines.join('\n').trimEnd()}\n`;
}

const generatedAt = new Date().toISOString();
const issues = auditRouteSafety(rivers);
const summary = routeSafetyAuditSummary(issues);

await mkdir(path.dirname(jsonPath), { recursive: true });
await writeGeneratedFile(
  jsonPath,
  `${JSON.stringify(
    {
      version: 1,
      generatedAt,
      routeCount: rivers.length,
      issueCount: issues.length,
      summary,
      issues,
    },
    null,
    2,
  )}\n`,
);
await writeGeneratedFile(markdownPath, makeMarkdown({ generatedAt, issues }));

console.log(`Route safety audit generated ${issues.length} issue(s) for ${rivers.length} routes.`);
console.log(JSON.stringify(summary));

async function writeGeneratedFile(filePath: string, contents: string) {
  const temporaryPath = `${filePath}.tmp-${process.pid}`;
  let lastError: unknown;
  for (let attempt = 0; attempt < 4; attempt += 1) {
    try {
      await writeFile(temporaryPath, contents, 'utf8');
      try {
        await rename(temporaryPath, filePath);
      } catch (error) {
        if ((error as NodeJS.ErrnoException).code !== 'EEXIST') throw error;
        await unlink(filePath);
        await rename(temporaryPath, filePath);
      }
      return;
    } catch (error) {
      lastError = error;
      const code = (error as NodeJS.ErrnoException).code;
      if (!['EACCES', 'EPERM', 'EEXIST', 'UNKNOWN'].includes(String(code)) || attempt === 3) throw error;
      await new Promise((resolve) => setTimeout(resolve, 50 * (attempt + 1)));
    }
  }
  throw lastError;
}
