import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

type Endpoint = {
  routeId: string; routeName: string; reach: string; state: string;
  endpoint: 'putIn' | 'takeOut' | 'accessPoint'; endpointName: string; latitude: number; longitude: number;
  matchedRiverName: string | null; distanceFeetToMatchedRiver: number | null;
  nearestMatchedLatitude: number | null; nearestMatchedLongitude: number | null;
  nearestWaterwayName: string | null; distanceFeetToNearestWaterway: number | null;
  nearestWaterwayLatitude: number | null; nearestWaterwayLongitude: number | null;
  nearestWaterbodyName: string | null; distanceFeetToNearestWaterbody: number | null;
  nearestWaterbodyLatitude: number | null; nearestWaterbodyLongitude: number | null;
  endpointOnWaterbody: boolean; severity: string; note: string;
};
type AuditReport = { endpoints: Endpoint[]; generatedAt: string };

const root = process.cwd();
const reportPath = path.join(root, 'docs', 'route-coordinate-river-audit.json');
const outputPath = path.join(root, 'docs', 'route-coordinate-failure-review.html');
const researchPath = path.join(root, 'docs', 'route-coordinate-needs-research.json');
const geometryRoot = path.join(root, 'public', 'data', 'canonical-river-geometries', 'routes');

function htmlEscape(value: string) {
  return value.replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character] ?? character));
}
function jsonForScript(value: unknown) { return JSON.stringify(value).replace(/</g, '\\u003c'); }

async function run() {
  const report = JSON.parse(await readFile(reportPath, 'utf8')) as AuditReport;
  const endpoints = report.endpoints.filter((endpoint) => endpoint.severity === 'failure');
  const routeEndpoints: Record<string, Record<string, Endpoint>> = {};
  for (const endpoint of report.endpoints) {
    routeEndpoints[endpoint.routeId] ??= {};
    routeEndpoints[endpoint.routeId][endpoint.endpoint] = endpoint;
  }
  const geometries: Record<string, unknown> = {};
  await Promise.all([...new Set(endpoints.map((endpoint) => endpoint.routeId))].map(async (routeId) => {
    try { geometries[routeId] = JSON.parse(await readFile(path.join(geometryRoot, `${routeId}.json`), 'utf8')); }
    catch { geometries[routeId] = null; }
  }));
  const payload = jsonForScript({ generatedAt: report.generatedAt, endpoints, routeEndpoints, geometries });
const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Paddle Today · Coordinate verification queue</title><link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"><style>
:root{font-family:system-ui,sans-serif;color:#17211b;background:#f4f7f4}*{box-sizing:border-box}body{margin:0}header{padding:18px 24px;background:#173f35;color:#fff}h1{margin:0 0 5px;font-size:22px}header p{margin:0;color:#c8e3d2;font-size:13px}.layout{display:grid;grid-template-columns:380px 1fr;height:calc(100vh - 82px)}aside{overflow:auto;padding:14px;background:#fff;border-right:1px solid #dce6df}.controls{display:grid;gap:7px}.controls input,.controls select{width:100%;padding:9px;border:1px solid #c8d5cc;border-radius:7px}.summary{font-size:12px;color:#53645a;margin:10px 0}.item{display:block;width:100%;text-align:left;border:1px solid #dce6df;background:#fbfdfb;border-radius:8px;margin:7px 0;padding:10px;cursor:pointer}.item:hover,.item.active{border-color:#2c8b61;background:#eff9f1}.item strong,.item small{display:block}.item strong{font-size:13px}.item small{color:#627268;margin-top:3px}.distance{color:#a23d21!important;font-weight:700}.main{position:relative}.map{position:absolute;inset:0}.panel{position:absolute;z-index:1000;top:14px;right:14px;width:min(420px,calc(100% - 28px));background:#fffffff2;border:1px solid #ccd9d0;border-radius:10px;padding:14px;box-shadow:0 4px 18px #1232}.panel h2{margin:0 0 5px;font-size:17px}.panel p{margin:5px 0;font-size:13px;line-height:1.4}.panel a{color:#176b4b}.coords{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin:8px 0}.coords label{font-size:11px;color:#53645a}.coords input{display:block;width:100%;padding:6px;border:1px solid #c8d5cc;border-radius:5px}.copy{padding:7px 9px;border:0;border-radius:5px;background:#176b4b;color:#fff;cursor:pointer}.triage{display:flex;gap:6px;flex-wrap:wrap;margin:8px 0}.triage button{padding:6px 8px;border:0;border-radius:5px;cursor:pointer}.accept{background:#d8f1df}.research{background:#fff0cf}.skip{background:#f7d9d2}.legend{display:flex;flex-wrap:wrap;gap:10px;font-size:11px;color:#4e6055}.dot{display:inline-block;width:10px;height:10px;border-radius:50%;margin-right:4px}.red{background:#d0442e}.orange{background:#e08a28}.blue{background:#2a73b8}.green{background:#2b9561}
</style></head><body><header><h1>Paddle Today · Coordinate verification queue</h1><p>${endpoints.length} endpoints requiring verification · generated ${htmlEscape(report.generatedAt)} · click a row to inspect the endpoint against route geometry and NHD context</p></header><div class="layout"><aside><div class="controls"><input id="search" type="search" placeholder="Filter route, reach, or endpoint…"></div><div id="summary" class="summary"></div><div id="list"></div></aside><main class="main"><div id="map" class="map"></div><section id="panel" class="panel"><h2>Select an endpoint</h2><p>Choose an endpoint from the verification queue.</p></section></main></div><script id="payload" type="application/json">${payload}</script><script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script>
const data=JSON.parse(document.getElementById('payload').textContent), endpoints=data.endpoints, geometries=data.geometries;const map=L.map('map',{preferCanvas:true}).setView([44,-92],6);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors'}).addTo(map);let layers=[],selected=-1;
const reviewKey=e=>e.routeId+':'+e.endpoint;const saved=JSON.parse(localStorage.getItem('paddletoday:coordinate-review:v1')||'{}');const statuses=saved.statuses||{};const drafts=saved.drafts||{};endpoints.forEach(e=>{const d=drafts[reviewKey(e)];if(d){e.latitude=d.latitude;e.longitude=d.longitude}});function persist(){localStorage.setItem('paddletoday:coordinate-review:v1',JSON.stringify({statuses,drafts}))}document.querySelector('.controls').insertAdjacentHTML('beforeend','<select id="status-filter"><option value="open">Open and unresolved</option><option value="all">All failures</option><option value="accepted">Accepted</option><option value="research">Needs research</option><option value="skipped">Skipped</option></select><button id="export" class="copy">Export accepted corrections</button>');function clearLayers(){layers.forEach((layer)=>map.removeLayer(layer));layers=[]}function link(lat,lon,text){return '<a target="_blank" rel="noreferrer" href="https://www.google.com/maps/search/?api=1&query='+lat+','+lon+'">'+text+'</a>'}function marker(lat,lon,color,label){const m=L.circleMarker([lat,lon],{radius:8,color:'#fff',weight:2,fillColor:color,fillOpacity:.95}).bindTooltip(label).addTo(map);layers.push(m)}
function correctionText(e){return e.endpoint+': '+e.latitude.toFixed(6)+', '+e.longitude.toFixed(6)+' // '+e.routeId+' · '+e.endpointName}function redraw(index){show(index)}function show(index){selected=index;const e=endpoints[index];clearLayers();const geometry=geometries[e.routeId];if(geometry){const line=L.geoJSON(geometry,{style:{color:'#2b9561',weight:4,opacity:.8}}).addTo(map);layers.push(line);map.fitBounds(line.getBounds().pad(.18))}else map.setView([e.latitude,e.longitude],13);marker(e.latitude,e.longitude,'#d0442e','Endpoint: '+e.endpointName);if(e.nearestMatchedLatitude!==null)marker(e.nearestMatchedLatitude,e.nearestMatchedLongitude,'#e08a28','Matched '+(e.matchedRiverName||'flowline'));if(e.nearestWaterwayLatitude!==null)marker(e.nearestWaterwayLatitude,e.nearestWaterwayLongitude,'#2a73b8','Nearest '+(e.nearestWaterwayName||'waterway'));if(e.nearestWaterbodyLatitude!==null)marker(e.nearestWaterbodyLatitude,e.nearestWaterbodyLongitude,'#2b9561','Nearest NHD waterbody');document.getElementById('panel').innerHTML='<h2>'+e.routeName+' · '+e.endpoint+'</h2><p><strong>'+e.endpointName+'</strong><br>'+e.reach+' · '+e.state+'</p><p>'+e.note+'</p><div class="coords"><label>Latitude<input id="coord-lat" type="number" step="0.000001" value="'+e.latitude.toFixed(6)+'"></label><label>Longitude<input id="coord-lon" type="number" step="0.000001" value="'+e.longitude.toFixed(6)+'"></label></div><button id="copy-correction" class="copy">Copy coordinate correction</button> <span id="copy-status"></span><p>Endpoint: '+link(e.latitude,e.longitude,e.latitude.toFixed(6)+', '+e.longitude.toFixed(6))+'<br>Matched flowline: '+(e.distanceFeetToMatchedRiver===null?'none':Math.round(e.distanceFeetToMatchedRiver)+' ft')+'<br>Nearest named waterway: '+(e.nearestWaterwayName||'none')+' ('+(e.distanceFeetToNearestWaterway===null?'—':Math.round(e.distanceFeetToNearestWaterway)+' ft')+')</p><p>Click the map to move this endpoint marker. The dashboard does not edit source files.</p><p><a target="_blank" rel="noreferrer" href="https://www.google.com/search?q='+encodeURIComponent(e.endpointName+' '+e.routeName+' '+e.state)+'">Search access source</a></p><div class="legend"><span><i class="dot red"></i>endpoint</span><span><i class="dot orange"></i>matched flowline</span><span><i class="dot blue"></i>nearest named waterway</span><span><i class="dot green"></i>NHD waterbody/area</span></div>';document.getElementById('coord-lat').addEventListener('change',()=>{e.latitude=Number(document.getElementById('coord-lat').value);redraw(index)});document.getElementById('coord-lon').addEventListener('change',()=>{e.longitude=Number(document.getElementById('coord-lon').value);redraw(index)});document.getElementById('copy-correction').addEventListener('click',async()=>{const status=document.getElementById('copy-status');try{await navigator.clipboard.writeText(correctionText(e));status.textContent='Copied'}catch{status.textContent='Copy unavailable; use the coordinate fields above'}})}
map.on('click',(event)=>{if(selected<0)return;endpoints[selected].latitude=event.latlng.lat;endpoints[selected].longitude=event.latlng.lng;show(selected)});function render(){const query=document.getElementById('search').value.toLowerCase();const visible=endpoints.map((e,i)=>({e,i})).filter(({e})=>(e.routeId+' '+e.routeName+' '+e.reach+' '+e.endpointName).toLowerCase().includes(query));document.getElementById('summary').textContent=visible.length+' of '+endpoints.length+' failures shown';document.getElementById('list').innerHTML=visible.map(({e,i})=>'<button class="item '+(i===selected?'active':'')+'" data-index="'+i+'"><strong>'+e.routeName+' · '+e.endpoint+'</strong><small>'+e.endpointName+' · '+e.routeId+'</small><small class="distance">'+(e.distanceFeetToMatchedRiver===null?'No matched flowline':Math.round(e.distanceFeetToMatchedRiver)+' ft from '+(e.matchedRiverName||'matched flowline'))+'</small></button>').join('');document.querySelectorAll('[data-index]').forEach((button)=>button.addEventListener('click',()=>show(Number(button.dataset.index))))}document.getElementById('search').addEventListener('input',render);render();if(endpoints.length)show(0);
function applyStatusFilter(){const filter=document.getElementById('status-filter').value;document.querySelectorAll('[data-index]').forEach(button=>{const status=statuses[reviewKey(endpoints[Number(button.dataset.index)])];button.style.display=filter==='all'||(filter==='open'&&!status)||status===filter?'':'none'})}function setStatus(status){if(selected<0)return;statuses[reviewKey(endpoints[selected])]=status;persist();render();applyStatusFilter()}function exportCorrections(){const rows=endpoints.filter(e=>statuses[reviewKey(e)]==='accepted').map(e=>({routeId:e.routeId,endpoint:e.endpoint,endpointName:e.endpointName,latitude:e.latitude,longitude:e.longitude}));const blob=new Blob([JSON.stringify(rows,null,2)+'\\n'],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='route-coordinate-corrections.json';a.click();URL.revokeObjectURL(url)}const observer=new MutationObserver(()=>{if(selected<0||document.getElementById('accept'))return;document.getElementById('panel').insertAdjacentHTML('beforeend','<div class="triage"><button id="accept" class="accept">Accept (A)</button><button id="research" class="research">Needs research (R)</button><button id="skip" class="skip">Skip (S)</button></div>');document.getElementById('accept').onclick=()=>setStatus('accepted');document.getElementById('research').onclick=()=>setStatus('research');document.getElementById('skip').onclick=()=>setStatus('skipped')});observer.observe(document.getElementById('panel'),{childList:true});map.on('click',(event)=>{if(selected<0)return;endpoints[selected].latitude=event.latlng.lat;endpoints[selected].longitude=event.latlng.lng;drafts[reviewKey(endpoints[selected])]={latitude:event.latlng.lat,longitude:event.latlng.lng};persist();show(selected)});document.getElementById('status-filter').addEventListener('change',()=>{render();applyStatusFilter()});document.getElementById('export').addEventListener('click',exportCorrections);document.addEventListener('keydown',(event)=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName))return;if(event.key.toLowerCase()==='j')show(Math.min(endpoints.length-1,selected+1));if(event.key.toLowerCase()==='k')show(Math.max(0,selected-1));if(event.key.toLowerCase()==='a')setStatus('accepted');if(event.key.toLowerCase()==='r')setStatus('research');if(event.key.toLowerCase()==='s')setStatus('skipped')});if(selected>=0)show(selected);</script></body></html>`;
  const contextScript = `<script>(function(){function renderCurrentRoute(){const pair=data.routeEndpoints[endpoints[selected]?.routeId];if(!pair)return;const old=document.getElementById('route-context');if(old)return;const putIn=pair.putIn,takeOut=pair.takeOut;document.getElementById('panel').insertAdjacentHTML('afterbegin','<div id="route-context" style="background:#eef7f0;border:1px solid #c9dfce;border-radius:6px;padding:8px;margin-bottom:8px;font-size:12px"><strong>Current app coordinates</strong><br>Put-in: '+putIn.latitude.toFixed(6)+', '+putIn.longitude.toFixed(6)+'<br>Take-out: '+takeOut.latitude.toFixed(6)+', '+takeOut.longitude.toFixed(6)+'</div>');marker(putIn.latitude,putIn.longitude,'#7b4ab5','Current app put-in: '+putIn.endpointName);marker(takeOut.latitude,takeOut.longitude,'#157a76','Current app take-out: '+takeOut.endpointName)}const observer=new MutationObserver(()=>{if(selected>=0)renderCurrentRoute()});observer.observe(document.getElementById('panel'),{childList:true});renderCurrentRoute()})();</script>`;
  const activeScript = `<script>(function(){function drawActiveReach(){if(window.__activeReachLayer)map.removeLayer(window.__activeReachLayer);const e=endpoints[selected],pair=data.routeEndpoints[e?.routeId],geometry=geometries[e?.routeId]?.geometry;if(!pair||!geometry?.coordinates)return;const lines=geometry.type==='MultiLineString'?geometry.coordinates:[geometry.coordinates];let start=null,end=null;const distance=(coordinate,point)=>((coordinate[0]-point.longitude)*Math.cos(point.latitude*Math.PI/180))**2+(coordinate[1]-point.latitude)**2;lines.forEach((line,lineIndex)=>line.forEach((coordinate,index)=>{if(!start||distance(coordinate,pair.putIn)<start.distance)start={lineIndex,index,distance};if(!end||distance(coordinate,pair.takeOut)<end.distance)end={lineIndex,index,distance}}));let coordinates;if(start&&end&&start.lineIndex===end.lineIndex){coordinates=lines[start.lineIndex].slice(Math.min(start.index,end.index),Math.max(start.index,end.index)+1).map(coordinate=>[coordinate[1],coordinate[0]])}else{coordinates=[[pair.putIn.latitude,pair.putIn.longitude],[pair.takeOut.latitude,pair.takeOut.longitude]]}window.__activeReachLayer=L.polyline(coordinates,{color:'#145c3b',weight:7,opacity:.95}).bindTooltip('Active reach between current put-in and take-out').addTo(map);layers.push(window.__activeReachLayer)}new MutationObserver(drawActiveReach).observe(document.getElementById('panel'),{childList:true});drawActiveReach();})();</script>`;
  const editingHelpScript = `<script>(function(){const panel=document.getElementById('panel');const observer=new MutationObserver(()=>{if(selected<0||document.getElementById('editing-help'))return;panel.insertAdjacentHTML('afterbegin','<div id="editing-help" style="background:#fff8df;border:1px solid #ead38a;border-radius:6px;padding:9px;margin-bottom:8px;font-size:12px;line-height:1.35"><strong>How to correct this endpoint</strong><br>1. Click the exact river/bridge intersection on the map. The red marker and coordinate fields become the proposed replacement.<br>2. Confirm the red marker is on the water, then choose <b>Accept</b> and export the correction file.<br><span style="color:#7b4ab5">Purple</span> = current app coordinate · <span style="color:#d0442e">red</span> = proposed/editing coordinate · <span style="color:#e08a28">orange</span> = nearest matched river point. The dashboard never edits source files automatically.</div>');const actions=document.createElement('div');actions.style='display:flex;gap:6px;flex-wrap:wrap;margin:6px 0';actions.innerHTML='<button id="use-river-point" class="copy">Use nearest river point</button><button id="reset-app-point" class="copy" style="background:#66756c">Reset to app coordinate</button>';panel.insertBefore(actions,panel.querySelector('.coords'));document.getElementById('use-river-point').onclick=()=>{const e=endpoints[selected];if(e.nearestMatchedLatitude===null)return;e.latitude=e.nearestMatchedLatitude;e.longitude=e.nearestMatchedLongitude;drafts[reviewKey(e)]={latitude:e.latitude,longitude:e.longitude};persist();show(selected)};document.getElementById('reset-app-point').onclick=()=>{const e=endpoints[selected],pair=data.routeEndpoints[e.routeId],point=e.endpoint==='putIn'?pair.putIn:pair.takeOut;e.latitude=point.latitude;e.longitude=point.longitude;delete drafts[reviewKey(e)];persist();show(selected)}});observer.observe(panel,{childList:true});})();</script>`;
  const mapClarityScript = `<script>(function(){const originalFitBounds=map.fitBounds.bind(map);map.fitBounds=function(){const e=endpoints[selected];if(e)map.setView([e.latitude,e.longitude],14);else originalFitBounds.apply(map,arguments)};marker=function(lat,lon,color,label){if(label.indexOf('Matched ')===0||label.indexOf('Nearest ')===0)return;const m=L.circleMarker([lat,lon],{radius:8,color:'#fff',weight:2,fillColor:color,fillOpacity:.95}).bindTooltip(label).addTo(map);layers.push(m)};setTimeout(()=>{if(selected>=0)show(selected)},0)})();</script>`;
  await writeFile(outputPath, html.replace('</script></body></html>', `</script>${contextScript}${activeScript}${editingHelpScript}${mapClarityScript}</body></html>`));
  await writeFile(researchPath, `${JSON.stringify({
    generatedAt: report.generatedAt,
    status: 'needs-research',
    count: endpoints.length,
    items: endpoints.map((endpoint) => ({
      routeId: endpoint.routeId,
      endpoint: endpoint.endpoint,
      endpointName: endpoint.endpointName,
      latitude: endpoint.latitude,
      longitude: endpoint.longitude,
      reason: 'Coordinate remains unresolved after automated waterway and polygon checks; verify visually and against an authoritative access source before changing it.',
    })),
  }, null, 2)}\n`);
  console.log(`Generated ${path.relative(root, outputPath)} with ${endpoints.length} failure(s).`);
}
run().catch((error: unknown) => { console.error(error instanceof Error ? error.message : error); process.exit(1); });
// route context marker enhancement is injected into the generated page below.
