import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { routeAccessReviewHolds } from '../src/data/route-access-review-holds';
import { routeCoordinateReviewReleases } from '../src/data/route-coordinate-review-releases';
import { routeInventory } from '../src/data/rivers';

type SuggestionReport = {
  generatedAt: string;
  items: Array<{ routeId: string }>;
};

const root = process.cwd();
const inputPath = path.join(root, 'docs', 'route-coordinate-suggestions.json');
const outputPath = path.join(root, 'src', 'data', 'generated', 'withheld-route-slugs.ts');

async function main() {
  const report = JSON.parse(await readFile(inputPath, 'utf8')) as SuggestionReport;
  const routeIdSet = new Set([
    ...report.items.map((item) => item.routeId),
    ...Object.keys(routeAccessReviewHolds),
  ]);
  const knownRouteIds = new Set(routeInventory.map((route) => route.id));
  for (const routeId of Object.keys(routeCoordinateReviewReleases)) {
    if (!knownRouteIds.has(routeId)) throw new Error(`Reviewed release ${routeId} is not present in route inventory.`);
    // A release can retire a manual hold as well as a stale suggestion. This
    // keeps the release decision in one explicit reviewed map instead of
    // requiring a duplicate placeholder in the suggestion snapshot.
    routeIdSet.delete(routeId);
  }
  const routeIds = [...routeIdSet].sort();
  const source = `// Generated by scripts/generate-withheld-route-slugs.ts.\n`
    + `// Coordinate audit/suggestion source: ${report.generatedAt}\n`
    + `// Human-reviewed release exceptions: ${Object.keys(routeCoordinateReviewReleases).length}\n`
    + `export const coordinateWithheldRouteSlugs = ${JSON.stringify(routeIds, null, 2)} as const;\n`;
  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, source);
  console.log(`Generated ${path.relative(root, outputPath)} with ${routeIds.length} withheld route(s).`);
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
