import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

type SuggestionReport = {
  generatedAt: string;
  items: Array<{ routeId: string }>;
};

const root = process.cwd();
const inputPath = path.join(root, 'docs', 'route-coordinate-suggestions.json');
const outputPath = path.join(root, 'src', 'data', 'generated', 'withheld-route-slugs.ts');

async function main() {
  const report = JSON.parse(await readFile(inputPath, 'utf8')) as SuggestionReport;
  const routeIds = [...new Set(report.items.map((item) => item.routeId))].sort();
  const source = `// Generated by scripts/generate-withheld-route-slugs.ts.\n`
    + `// Coordinate audit/suggestion source: ${report.generatedAt}\n`
    + `export const coordinateWithheldRouteSlugs = ${JSON.stringify(routeIds, null, 2)} as const;\n`;
  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, source);
  console.log(`Generated ${path.relative(root, outputPath)} with ${routeIds.length} withheld route(s).`);
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
