import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { routeInventory, rivers } from '../src/data/rivers';

const root = resolve(process.cwd());
const operationsDir = resolve(root, 'docs/operations');
mkdirSync(operationsDir, { recursive: true });
const tasks = JSON.parse(readFileSync(resolve(operationsDir, 'tasks.json'), 'utf8')).tasks as Array<{ id: string; title: string; lane: string; kind: string; summary: string; evidence?: string[] }>;
const runs = JSON.parse(readFileSync(resolve(operationsDir, 'runs.json'), 'utf8')).runs as Array<{ id: string; kind: string; startedAt: string; status: string; taskId?: string; summary?: string }>;
const registry = JSON.parse(readFileSync(resolve(operationsDir, 'state-registry.json'), 'utf8')) as { canonicalStates: Array<{ id: string; name: string }> };
const scored = new Set(rivers.map((route) => route.slug));
const blocked = tasks.filter((task) => task.lane === 'blocked');
const category = (text: string) => { const value = text.toLowerCase(); if (value.includes('gauge') || value.includes('provider')) return 'gauge/provider'; if (value.includes('coordinate') || value.includes('geometry')) return 'coordinates/geometry'; if (value.includes('camp')) return 'camping'; if (value.includes('safety') || value.includes('dam')) return 'safety'; if (value.includes('access') || value.includes('endpoint')) return 'access/endpoints'; if (value.includes('threshold') || value.includes('flow')) return 'thresholds'; return 'policy/other'; };
const dossiers = registry.canonicalStates.map((state) => { const inventory = routeInventory.filter((route) => String(route.state).toUpperCase() === state.id || route.state === state.name); const scoredRoutes = inventory.filter((route) => scored.has(route.slug)); const stateTasks = tasks.filter((task) => task.kind === 'state_coverage' && (task.id.toLowerCase().includes(state.id.toLowerCase()) || task.summary.toLowerCase().includes(state.name.toLowerCase()))); const relevantRuns = runs.filter((run) => stateTasks.some((task) => task.id === run.taskId) || (run.summary ?? '').toLowerCase().includes(state.name.toLowerCase())); return { stateId: state.id, stateName: state.name, inventoryCount: inventory.length, scoredCount: scoredRoutes.length, planningCount: inventory.length - scoredRoutes.length, scoredCoveragePercent: inventory.length ? Math.round((scoredRoutes.length / inventory.length) * 100) : 0, discoveryTasks: stateTasks.map((task) => ({ id: task.id, lane: task.lane, summary: task.summary, evidenceCount: task.evidence?.length ?? 0 })), recentEvidenceRuns: relevantRuns.slice(-10), doneOnlyWhen: ['inventory quality audit', 'bounded fresh discovery sweep', 'no candidate clears all scored-route gates'] }; });
const groups = Object.values(blocked.reduce<Record<string, { category: string; taskIds: string[]; titles: string[]; summaries: string[] }>>((result, task) => { const key = category(`${task.title} ${task.summary}`); result[key] ??= { category: key, taskIds: [], titles: [], summaries: [] }; result[key].taskIds.push(task.id); result[key].titles.push(task.title); result[key].summaries.push(task.summary); return result; }, {}));
writeFileSync(resolve(operationsDir, 'saturation-dossiers.json'), JSON.stringify({ generatedAt: new Date().toISOString(), policy: 'bounded-discovery-required-before-done', dossiers }, null, 2) + '\n');
writeFileSync(resolve(operationsDir, 'blocker-resolution-queue.json'), JSON.stringify({ generatedAt: new Date().toISOString(), groups, nextAction: 'Resolve the highest-leverage group only with fresh manager-grade evidence or an approved provider/policy change.' }, null, 2) + '\n');
console.log(JSON.stringify({ saturationDossiers: dossiers.length, blockerGroups: groups.length }));
